### ISSUE TITLE
the repo does seems to work with current version of stan

### ISSUE THREAD

**Issue by chanansh** [leopoldavezac/BayesianMMM#4]
the interface to stan has been changed. Yet, the requirements.txt file does not state versions so it is hard to find which version was used. For example, now you `import stan` rather than `import pystan`. Moreover, the interface to `StanModel` has changed to `model.Model` etc.

**Comment by leopoldavezac** [comment]
I have added the pystan version to the environment.yaml file. Instructions on how to install have been added to the README.md as well.
