### ISSUE TITLE
RuntimeError: Error calling get_param_names

### ISSUE THREAD

**Issue by chanansh** [leopoldavezac/BayesianMMM#5]
RuntimeError: Error calling get_param_names: `Exception: variable does not exist; processing stage=data initialization; variable name=N; base type=int (in '/var/folders/7l/27620by50812sxd514rjz_840000gn/T/httpstan_zc6301jx/model_6gauqelw.stan', line 14, column 3 to column 18)`

**Comment by leopoldavezac** [comment]
It seems to be due to your version of pystan. If you use the specified version of pystan you should be fine.
